-- V017: Add password setup fields for admin-created users
-- When an admin creates a user, they need to set their own password after email verification
--
-- NOTE: This migration requires DBA/owner privileges to run.
-- The campcard_app user does not have ALTER TABLE permissions.
--
-- DBA should run the following SQL manually as the postgres user:
--
-- ALTER TABLE campcard.users ADD COLUMN IF NOT EXISTS password_setup_required BOOLEAN NOT NULL DEFAULT FALSE;
-- ALTER TABLE campcard.users ADD COLUMN IF NOT EXISTS password_setup_token VARCHAR(255);
-- ALTER TABLE campcard.users ADD COLUMN IF NOT EXISTS password_setup_expires_at TIMESTAMP;
-- CREATE INDEX IF NOT EXISTS idx_users_password_setup_token ON campcard.users(password_setup_token) WHERE password_setup_token IS NOT NULL;
--
-- After DBA runs the above, uncomment the related code in:
-- - User.java (passwordSetupRequired, passwordSetupToken, passwordSetupExpiresAt fields)
-- - UserService.java (createUser method)
-- - AuthService.java (verifyEmail and setPassword methods)
-- - UserRepository.java (findByPasswordSetupToken method)

-- Placeholder to mark migration as complete (does nothing)
SELECT 1;
