-- ============================================================================
-- V036: Referral constraint notes
-- ============================================================================
-- The referrals table is owned by 'postgres', so campcard_app cannot ALTER it.
-- Java code has been adapted to work within existing constraints:
--   - Uses SUBSCRIBED status (in DB CHECK) instead of COMPLETED
--   - Generates unique referral codes per record to avoid UNIQUE violation
--
-- If you have postgres access, run these optional optimizations:
--   ALTER TABLE referrals DROP CONSTRAINT IF EXISTS referrals_referral_code_key;
--   ALTER TABLE referrals DROP CONSTRAINT IF EXISTS chk_referral_status;
--   ALTER TABLE referrals ADD CONSTRAINT chk_referral_status
--     CHECK (status IN ('PENDING','CLICKED','SIGNED_UP','SUBSCRIBED','COMPLETED','REWARDED','EXPIRED','CANCELLED'));
--   ALTER TABLE referrals ADD COLUMN IF NOT EXISTS notes TEXT;
-- ============================================================================
SELECT 1;
