/// <reference types="node" />

declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_API_BASE_URL?: string;
    EXPO_PUBLIC_AUTHORIZENET_PUBLIC_CLIENT_KEY?: string;
    EXPO_PUBLIC_AUTHORIZENET_API_LOGIN_ID?: string;
    EXPO_PUBLIC_GOOGLE_MAPS_API_KEY?: string;
    EXPO_PUBLIC_FIREBASE_API_KEY?: string;
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
    EXPO_PUBLIC_FIREBASE_PROJECT_ID?: string;
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET?: string;
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
    EXPO_PUBLIC_FIREBASE_APP_ID?: string;
    EXPO_PUBLIC_ENABLE_CUSTOMER_REFERRALS?: string;
    EXPO_PUBLIC_ENABLE_PUSH_NOTIFICATIONS?: string;
    EXPO_PUBLIC_ENABLE_BIOMETRIC_AUTH?: string;
    EXPO_PUBLIC_ENVIRONMENT?: string;
  }
}
